### ISSUE TITLE
Mobile design

### ISSUE THREAD

**Issue by ScriptRaccoon** [bradtraversy/loruki-website#3]
Thanks a lot for the tutorial! I have noticed that the mobile design is not quite right. You have made the design by shrinking the browser, but by checking out the site on a phone or using the dev tools of Firefox / Chrome, I have noticed that the text is cropped. Screenshot: http://prntscr.com/v733fw. I am not sure what is the best fix for it. But it has to do with the card below in the showcase section, since it prevents the container from shrinking down.

**Comment by bradtraversy** [comment]
Thanks for that. I went ahead and changed the width for the form to 300px on mobile to fix the issue
